name: deploy-to-k8s

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      type:
        required: true
        type: string
      namespace:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      KUBECONFIG:
        required: true
      GHCR_TOKEN:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine deployment path
        id: path
        run: |
          if [[ "${{ inputs.namespace }}" == "core" ]]; then
            echo "SERVICE_PATH=infrastructure/k8s/overlays/production/${{ inputs.namespace }}/${{ inputs.deployment_name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.namespace }}" == "api" ]]; then
            echo "SERVICE_PATH=infrastructure/k8s/overlays/production/${{ inputs.namespace }}/${{ inputs.deployment_name }}/${{ inputs.type }}" >> $GITHUB_OUTPUT
          else
            echo "Unsupported namespace: ${{ inputs.namespace }}"
            exit 1
          fi

      - name: Build and push image
        run: |
          docker build \
            --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            -t ghcr.io/study-words/${{ inputs.namespace }}-${{ inputs.deployment_name }}:${{ github.sha }} .
          docker push ghcr.io/study-words/${{ inputs.namespace }}-${{ inputs.deployment_name }}:${{ github.sha }}

      - name: Checkout infrastructure repo
        uses: actions/checkout@v4
        with:
          repository: study-words/infrastructure
          token: ${{ secrets.GH_PAT }}
          path: infrastructure

      - name: Set image tag
        run: |
          kustomize edit set image "ghcr.io/study-words/${{ inputs.namespace }}-${{ inputs.deployment_name }}=ghcr.io/study-words/${{ inputs.namespace }}-${{ inputs.deployment_name }}:${{ github.sha }}"
        working-directory: ${{ steps.path.outputs.SERVICE_PATH }}

      - name: Setup kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      - name: Deploy
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          kubectl apply -k infrastructure/k8s/overlays/${{ inputs.environment }}

      - name: Wait for deployment rollout
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: kubectl rollout status deployment/${{ inputs.deployment_name }} -n ${{ inputs.namespace }} --timeout=60s
